name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 2 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue is stale because it has been open 7 days with no activity after asking for more info. Comment or this will be closed in 3 days.'
          stale-pr-message: 'This PR is stale because it has been open 45 days with no activity. Comment or this will be closed in 21 days.'
          close-issue-message: 'This issue was closed because it has been stalled for 10 days with no activity. This can be reopened if additional information is provided.'
          close-pr-message: 'This PR was closed because it has been stalled for 66 days with no activity.'
          days-before-issue-stale: 7
          days-before-pr-stale: 45
          days-before-issue-close: 3
          days-before-pr-close: 21
          any-of-labels: "More info"
